runtime: python
env: flex

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "firebase-config/diagnoskin-48e89-firebase-adminsdk-2at6m-586f82c415.json"

entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

# handlers:
# - url: /.*
#   secure: always
#   redirect_http_response_code: 301
#   script: auto

# instance_class: B8
# manual_scaling:
#   instances: 1
manual_scaling:
  instances: 1
resources:
  cpu: 2
  memory_gb: 8
  disk_size_gb: 10
