runtime: python37

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "firebase-config/diagnoskin-48e89-firebase-adminsdk-2at6m-586f82c415.json"

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

instance_class: B8
basic_scaling:
  max_instances: 4
  idle_timeout: 10m
